baseURL = 'https://blog.perfectroot.wiki'
languageCode = 'en-us'
title = 'P3rfectr00t'
theme = 'hugo-theme-stack'
timeZone = 'Africa/Nairobi'

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
    identifier = "home"
    [menu.main.params]
        icon = "home"
        newTab = false
[[menu.main]]
    name = "Archives"
    url = "/archives"
    weight = 20
    identifier = "Archives"
    [menu.main.params]
        icon = "archives"
        newTab = false
[[menu.main]]
    name = "Search"
    url = "/search"
    weight = 30
    identifier = "Search"
    [menu.main.params]
        icon = "search"
        newTab = false
[[menu.main]]
    name = "Links"
    url = "/links"
    weight = 40
    identifier = "Links"
    [menu.main.params]
        icon = "link"
        newTab = false

 [[menu.social]]
    name = "github"
    url = "https://github.com/p3rf3ctr00t/"
    weight = 10
    identifier = "Github"
    [menu.social.params]
        icon ="brand-github"
        newTab = false
 [[menu.social]]
    name = "X"
    url = "https://x.com/p3rf3ctr00t"
    weight = 20
    identifier = "X"
    [menu.social.params]
        icon ="brand-twitter"
        newTab = false
 [[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/company/p3rf3ctr00t/"
    weight = 20
    identifier = "linkedin"
    [menu.social.params]
        icon ="brand-linkedin"
        newTab = false
